version: "3.8"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=http://192.168.50.45:3333
    user: '0'
    ports:
      - "3333:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana
    networks:
      - common-tool
networks:
  common-tool:
    external: true
    name: common-tool

