version: '3'
services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      - 8978:8978
    volumes:
      - ./cloudbeaver_data:/opt/cloudbeaver/workspace
    networks:
      - common-tool

networks:
  common-tool:
    external: true
    name: common-tool