version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest  
    container_name: portainer
    privileged: true  
    ports:
      - "9090:9000"
    volumes:
      - "./portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    
volumes:
  portainer_data: