version: '3.9'

services:
  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    ports:
      - "8788:8080"
        #extra_hosts:
        #- "host.docker.internal:host-gateway"
    networks:
      - common-tool
    volumes:
      - ./open-webui-local:/app/backend/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "11434:11434"  # Ollama 기본 포트
    volumes:
      - ./ollama_data:/root/.ollama
    restart: always
    #network_mode: host
    networks:
      - common-tool

networks:
  common-tool:
    external: true
